### ISSUE TITLE
Your question on my repo

### ISSUE THREAD

**Issue by nibblebits** [lometur/haveibeenpwned#1]
Hello,

I left a comment here in regards to the comment you wrote on my commit. I couldn't find a way to send you a message on Github its a feature they really should add hey? haha.

Anyway I just wanted to let you know that I can't answer your question on my commit like that as I like to keep the commit logs clean for fresh users rather than many comments all over the commuted code. Please instead submit the question to my Q&A on where you bought the course and I will answer you. Be sure to include code snippets.

Glad you liked the course :) 
Many thanks,
Dan

**Comment by lometur** [comment]
Ahh apologies. I will do that right away.

**Comment by nibblebits** [comment]
No worries thanks
